module Selenium
  module WebDriver
    class BiDi
      class Cookies
        @cookies: untyped

        def initialize: () -> void

        def all: () -> untyped

        def add_cookie: (untyped name, untyped value) -> untyped

        def remove_cookie: (untyped name) -> untyped

        def []=: (untyped key, untyped value) -> untyped

        def []: (untyped key) -> untyped

        def delete: (untyped key) -> untyped

        def serialize: () -> untyped
      end
    end
  end
end
