module Selenium
  module WebDriver
    class BiDi
      class Credentials
        @username: untyped

        @password: untyped

        attr_accessor username: untyped

        attr_accessor password: untyped

        def initialize: (?username: untyped?, ?password: untyped?) -> void

        def serialize: () -> (nil | { type: "password", username: untyped, password: untyped })
      end
    end
  end
end
