module Selenium
  module WebDriver
    class BiDi
      class InterceptedResponse < InterceptedItem
        @reason: untyped

        @credentials: untyped

        @headers: untyped

        @set_cookie_headers: untyped

        attr_accessor reason: untyped

        def initialize: (untyped network, untyped request) -> void

        def continue: () -> untyped

        def credentials: (?username: untyped?, ?password: untyped?) -> untyped

        def headers: () -> untyped

        def set_cookie_headers: (?untyped? set_cookie_headers) -> untyped
      end
    end
  end
end
