module Selenium
  module WebDriver
    class BiDi
      class InterceptedRequest < InterceptedItem
        # We now rely on the modules above to initialize @headers and @cookies as Hashes
        @method: untyped

        @url: untyped

        @body: untyped

        @headers: untyped

        @cookies: untyped

        attr_accessor method: untyped

        attr_accessor url: untyped

        attr_reader body: untyped

        def initialize: (untyped network, untyped request) -> void

        def continue: () -> untyped

        def fail: () -> untyped

        def body=: (untyped value) -> untyped

        def headers: () -> untyped

        def cookies: () -> untyped
      end
    end
  end
end
